# Generated by Django 5.2 on 2025-08-28 14:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(db_index=True, help_text="Unique batch identifier like 'FA20-BCS' or 'SP21-CS'", max_length=50, unique=True)),
                ('batch_name', models.CharField(help_text="Descriptive name like 'Fall 2020 Bachelor of Computer Science'", max_length=200)),
                ('program', models.CharField(help_text="Program name like 'Computer Science', 'Software Engineering', etc.", max_length=100)),
                ('degree_level', models.CharField(help_text="Bachelor's, Master's, PhD, etc.", max_length=50)),
                ('start_year', models.IntegerField(help_text='Year the batch started')),
                ('end_year', models.IntegerField(help_text='Expected graduation year')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this batch is currently active')),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'ordering': ['-start_year', 'batch_code'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile picture of the instructor', null=True, upload_to='instructor_photos/')),
                ('faculty_status', models.CharField(choices=[('PERM', 'Permanent Faculty'), ('VISIT', 'Visiting Faculty'), ('LEAVE', 'On Leave')], default='PERM', help_text='Current employment status of the faculty member', max_length=5)),
                ('department', models.CharField(blank=True, help_text='Department or division', max_length=100)),
                ('office_location', models.CharField(blank=True, help_text='Office room number or location', max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('date_joined', models.DateField(blank=True, help_text='Date when instructor joined the institution', null=True)),
                ('leave_start_date', models.DateField(blank=True, help_text='Start date of leave (if applicable)', null=True)),
                ('leave_end_date', models.DateField(blank=True, help_text='Expected end date of leave (if applicable)', null=True)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(help_text="Course code like 'CS101', 'MATH201'", max_length=20, unique=True)),
                ('title', models.CharField(help_text="Course title like 'Introduction to Python'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed course description')),
                ('credit_hours', models.PositiveSmallIntegerField(default=3, help_text='Number of credit hours for this course')),
                ('course_type', models.CharField(choices=[('CORE', 'Core Course'), ('ELEC', 'Elective Course'), ('LAB', 'Lab Course'), ('PROJ', 'Project/Thesis')], default='CORE', help_text='Type of course (Core/Elective/Lab/Project)', max_length=4)),
                ('department', models.CharField(blank=True, help_text='Department offering this course', max_length=100)),
                ('prerequisite_courses', models.ManyToManyField(blank=True, help_text='Courses that must be completed before taking this course', to='Attendance.course')),
            ],
            options={
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(help_text="Section identifier like 'A', 'B', 'Gold', 'Silver'", max_length=50)),
                ('max_students', models.PositiveIntegerField(blank=True, help_text='Maximum number of students allowed in this section', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this section is currently active')),
                ('batch', models.ForeignKey(help_text='The batch this section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Attendance.batch')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['batch', 'section_name'],
                'unique_together': {('batch', 'section_name')},
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(help_text="Semester like 'Fall 2024', 'Spring 2025'", max_length=20)),
                ('academic_year', models.CharField(help_text="Academic year like '2024-25'", max_length=10)),
                ('class_days', models.CharField(blank=True, help_text="Days of week like 'Mon,Wed,Fri' or 'Tue,Thu'", max_length=20)),
                ('start_time', models.TimeField(blank=True, help_text='Class start time', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Class end time', null=True)),
                ('classroom', models.CharField(blank=True, help_text='Room number or location', max_length=50)),
                ('rtsp_stream_url', models.CharField(blank=True, help_text='RTSP stream URL for the classroom camera (e.g., rtsp://username:password@ip:port/stream)', max_length=500, null=True, verbose_name='RTSP Stream URL')),
                ('max_enrollment', models.PositiveIntegerField(blank=True, help_text='Maximum number of students allowed in this class', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this class is currently active')),
                ('start_date', models.DateField(blank=True, help_text='Class start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Class end date', null=True)),
                ('batch', models.ForeignKey(blank=True, help_text="DEPRECATED: Use 'batches' field instead", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_classes', to='Attendance.batch')),
                ('batches', models.ManyToManyField(blank=True, help_text='The batches taking this class', related_name='classes', to='Attendance.batch')),
                ('course', models.ForeignKey(help_text='The course being taught', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='Attendance.course')),
                ('sections', models.ManyToManyField(blank=True, help_text='Specific sections taking this class (leave empty for whole batch)', related_name='classes', to='Attendance.section')),
                ('instructors', models.ManyToManyField(help_text='Instructor(s) teaching this class', related_name='classes', to='Attendance.teacher')),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'ordering': ['semester', 'course__course_code'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(db_index=True, help_text="Unique student ID like 'FA20-BCS-001'", max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('face_embedding_file', models.CharField(blank=True, help_text='Filename of the .npy embedding file located in the ATTENDANCE_MODELS_DIR.', max_length=255, null=True)),
                ('images_folder_path', models.CharField(blank=True, help_text="Absolute server path to folder containing student's images", max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether student is currently enrolled')),
                ('enrollment_date', models.DateField(blank=True, help_text='Date of enrollment', null=True)),
                ('batch', models.ForeignKey(blank=True, help_text='The batch this student belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='Attendance.batch')),
                ('section', models.ForeignKey(blank=True, help_text='The section this student belongs to within their batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='Attendance.section')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_classroom', models.CharField(help_text='Original classroom that was unavailable', max_length=50)),
                ('temporary_classroom', models.CharField(help_text='Temporary classroom being used', max_length=50)),
                ('temporary_rtsp_url', models.CharField(blank=True, help_text='Temporary RTSP stream URL for the alternate classroom', max_length=500, null=True)),
                ('override_date', models.DateField(help_text='Date when this override is/was active')),
                ('reason', models.TextField(help_text='Reason for classroom change (e.g., camera malfunction, room unavailable)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this override is currently active')),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_overrides', to='Attendance.class')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_overrides_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-override_date', '-created_at'],
                'unique_together': {('class_instance', 'override_date')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_type', models.CharField(choices=[('REG', 'Regular Enrollment'), ('REP', 'Repeat/Improvement'), ('AUD', 'Audit Only'), ('TRA', 'Transfer Credit')], default='REG', help_text='Type of enrollment (Regular/Repeat/Audit/Transfer)', max_length=3)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, help_text='When the student was enrolled in this class')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this enrollment is currently active')),
                ('final_grade', models.CharField(blank=True, help_text="Final grade for this enrollment (e.g., 'A', 'B+', etc.)", max_length=5, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this enrollment')),
                ('class_instance', models.ForeignKey(help_text='The class the student is enrolled in', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='Attendance.class')),
                ('student', models.ForeignKey(help_text='The student enrolled in the class', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='Attendance.student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-enrollment_date'],
                'unique_together': {('student', 'class_instance')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('attendance_time', models.TimeField(blank=True, help_text='Time marking occurred', null=True)),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused')], default='P', max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this attendance record')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL)),
                ('class_instance', models.ForeignKey(help_text='The specific class instance this attendance is for', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='Attendance.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='Attendance.student')),
            ],
            options={
                'ordering': ['-attendance_date', '-attendance_time', 'student__last_name'],
                'unique_together': {('student', 'class_instance', 'attendance_date')},
            },
        ),
    ]
